{{- if .Values.controller.ingressClassResource.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/componenttest: controllertest
    app.kubernetes.io/branch: branch
    app.kubernetes.io/branch3: branch3
    app.kubernetes.io/branch10: branch10
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.controller.ingressClassResource.name }}
  {{- if .Values.controller.ingressClassResource.default }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: {{ .Values.controller.ingressClassResource.controllerValue }}
  {{- with .Values.controller.ingressClassResource.parameters }}
  parameters: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
